---
- name: Install webapp
  hosts: build
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure required packages are present
      apt:
        name:
          - maven
          - openjdk-11-jdk
          - git
        state: present

    - name: Create webapp directory
      file:
        path: /home/dmitry/webapp
        state: directory
        mode: '0755'

    - name: Clone repository
      git:
        repo: https://github.com/yankils/hello-world.git
        dest: /home/dmitry/webapp
        update: yes

    - name: Build webapp
      command: mvn package
      args:
        chdir: /home/dmitry/webapp

    - name: Copy war in localhost
      fetch:
        src: /home/dmitry/webapp/webapp/target/webapp.war
        dest: ./
        flat: yes
      become: yes

- name: Prod
  hosts: prod
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - tomcat9
        state: present

    - name: Copy war into tomcat directory
      copy:
        src: webapp.war
        dest: /var/lib/tomcat9/webapps


